import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import BottomNavbar from "@/components/BottomNavbar";

const poppins = Poppins({weight: ["400", "500", "600", "700", "800", "900"], subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light hide-scrollbar">
      <body className={poppins.className+ " bg-background-light dark:bg-background-dark"}>
        {children}
        <BottomNavbar/>
      </body>
    </html>
  );
}
